# Generated by Django 4.0.4 on 2022-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_alter_product_full_description_alter_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider',
        ),
        migrations.AddField(
            model_name='slider',
            name='slide',
            field=models.BooleanField(default=False),
        ),
    ]
