# Generated by Django 4.0.4 on 2022-06-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_alter_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='q_deal',
            field=models.BooleanField(default=False),
        ),
    ]
