# Generated by Django 4.0.4 on 2022-06-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0008_product_q_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='q_deal_req',
            field=models.BooleanField(default=False),
        ),
    ]
